---
name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run Tests
        run: npm test

      - name: Pedant
        id: pedant
        continue-on-error: true
        uses: goeselt/pedant@b8e404a982679f74a8cd9309de5d2492bc8030c3 # v1.2.3
        with:
          summary-github-step: true

      - name: Publish Pedant Report
        if: always()
        uses: goeselt/remark@7b12cbf2a7eabecc7fed7189ba79c5cf6c484952 # v1.0.4
        with:
          body: ${{ steps.pedant.outputs.summary }}
          comment-key: pedant
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-unchanged: true

      - name: Fail On Pedant Findings
        if: steps.pedant.outcome != 'success'
        run: exit 1
